<template>
  <div>
    <h1>Tipografia</h1>
    <h2>Tipografia</h2>
    <h3>Tipografia</h3>
    <h4>Tipografia</h4>
    <h5>Tipografia</h5>
    <h6>Tipografia</h6>
    <p>Tipografia</p>
  </div>
</template>